import { Inter } from 'next/font/google'
import './reset.css'
import './globals.css'
import { MantineProvider } from '@mantine/core'
import '@mantine/core/styles.css'
import { Notifications } from '@mantine/notifications'
import '@mantine/notifications/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'IQA',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
          <Notifications zIndex={1000} position="top-center" />
          <main className={inter.className}>
            {children}
          </main>
        </MantineProvider>
      </body>
    </html>
  )
}
