import React               from 'react';
import { MantineProvider } from '@mantine/core';
import { Notifications }   from '@mantine/notifications';
import { Inter }           from 'next/font/google';

import type { Metadata } from 'next';


import './reset.css';
import './globals.css';

import '@mantine/notifications/styles.css';
import '@mantine/core/styles.css';

const inter = Inter({ subsets: ['latin'] });

interface LayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title:       'IQA',
  description: 'Generated by create next app',
  keywords: `questions`
};

const RootLayout: React.FC<LayoutProps> = function({ children }) {
  return (
    <html lang="en">
    <body suppressHydrationWarning={true}>
    <MantineProvider>
      <Notifications zIndex={1000} position="top-center" />
      <main className={inter.className}>
        {children}
      </main>
    </MantineProvider>
    </body>
    </html>
  );
};

export default RootLayout;
